#!/usr/bin/env python

# Thomas Lee August 2016
# contact@tomlee.com.au

# Prints a table comparing the energy outputs files from a gromacs and
# amber MD run

# Amber energies are read from an mdinfo file and gromacs energies from
# the output of gmxdump eg `gmxdump -e ener.edr > ener.edr.dump`

import sys
import yaml
from numpy import spacing, float32

def print_results(gromos, amber, amber_exe):
    lfmt = "{:15s} {:14s} {:14s} {:5s} {:s}"
    fmt = "{: >15s} {: > 14.5e} {: > 14.5e} {: > 10.5e} {: > 10.3e} {:s}"
    print( lfmt.format(" quantity", " gromos", " "+amber_exe,
                    " ({}-gromos)".format(amber_exe),
                    " ({}-gromos)/gromos".format(amber_exe)) )
    for label in gromos.keys():
        if label in amber.keys():
            dif = amber[label]-gromos[label]
            if gromos[label] + amber[label] == 0 :
                x = 0. if dif == 0 else 1.
            else:
                x = (amber[label]-gromos[label])/gromos[label] if gromos[label] != 0 else 999
    
            warn = "**" if abs(x)>1e-5 else ('*' if abs(x)>1e-8 else '')
            print(fmt.format(label, gromos[label], amber[label], dif, x, warn))
    

if len(sys.argv) != 4:
    print("usage: {} energy.pmemd.yml energy.sander.yml energy.gromos.yml\n".format(sys.argv[0]))
    exit(1)

# mdinfo file from pmemd
pmemd_energy_file = sys.argv[1]
# mdinfo file from sander
sander_energy_file = sys.argv[2]
# output of `gmxdump -e ener.edr`
gromos_energy_file = sys.argv[3]

with open(pmemd_energy_file)  as f: pmemd  = yaml.load(f)
with open(sander_energy_file) as f: sander = yaml.load(f)
with open(gromos_energy_file) as f: gromos = yaml.load(f)

print_results(gromos, sander, "sander")
print_results(gromos, pmemd, "pmemd")

