#!/usr/bin/env python

import sys
import yaml
from gromos_format import parse_blocks, parse_simple_columns

#gromos log file

blocks = parse_blocks(sys.stdin)

energies = [ float(x) for x in blocks["ENERGY03"][1:39] ]

output = {}
output["bonds"] = energies[4]
output["angles"] = energies[5]
output["dihedrals"] = energies[7]
output["impropers"] = energies[6]
output["total_coulomb"] = energies[11]
output["total_vdw"] = energies[10]
output["total_potential"] = energies[2]

print(yaml.dump(output, default_flow_style=False))

