#!/usr/bin/env python

import sys
import yaml

#amber mdinfo file
lines = sys.stdin.readlines()
labellines = lines[:10]
valuelines = lines[10:]

labels = []
for line in labellines:
    labels.extend([ label.strip() for label in line.split()[1:] ])

values = []
for line in valuelines:
    values.extend([ float(label) for label in line.split()[1:] ])

calorie = 4.184 # J
amber = { label : value*calorie for label, value in zip(labels,values) }

output = {}
output["bonds"] = amber["E_bon"]
output["angles"] = amber["E_angle"]
output["dihedrals"] = amber["E_dih"]
#output["impropers"] = amber["E_imp"]
output["total_coulomb"] = amber["E_el"]+amber["E_14el"]
output["coulomb_1-4"] = amber["E_14el"]
output["total_vdw"] = amber["E_vdw"]+amber["E_14vdw"]
output["vdw_1-4"] = amber["E_14vdw"]
output["total_potential"] = amber["E_pot"]

print(yaml.dump(output, default_flow_style=False))

